In [10]:
# Create a string variable
city_name = 'City A'

# Print the value of the string variable
print(f"City: ",city_name)

City:  City A


In [20]:
def celsius_to_fahrenheit(celsius):
    return (celsius * 9/5) + 32


celsius = int(input('Enter temp: '))
fahrenheit = celsius_to_fahrenheit(celsius)
print(f"{celsius}°C is equal to {fahrenheit}°F")


Enter temp:  25


25°C is equal to 77.0°F


In [22]:
# Create a float var for carbon footprint
carbon_footprint = 500.75 # Kg CO2
print(f'Carbon footprint: ', carbon_footprint)

Carbon footprint:  500.75


In [28]:
is_sustainable = carbon_footprint < 400

print(f'Is the city sustainable? \nAns: ', is_sustainable)

Is the city sustainable? 
Ans:  False


In [64]:
num = input("Enter a number: ")

try:
    int(num)
    if type(int(num)) is int:
        print(f"{num} is an integer.")
except ValueError:
    print(f"{num} is not an integer.")

Enter a number:  5


5 is an integer.


In [66]:
num = [1,2,3,4,5]

if 1 in num:
    print("1 is in the list!")
else:
    print("1 is not in the list.")


1 is in the list!


In [68]:
op = input('Choose operation (+, -, *, /): ')
n1 = float(input('Enter num1: '))
n2 = float(input('Enter num2: '))
result = 0
if n2 == 0:
    print('Invalid')
if op == '+':
    result = n1 + n2
elif op == '-':
    result = n1 - n2
elif op == '*':
    result = n1 * n2
elif op == '/':
    result = n1 / n2
else:
    print('Invalid operation')

print(f'Result: ',result)


Choose operation (+, -, *, /):  *
Enter num1:  5
Enter num2:  2


Result:  10.0


In [60]:
# Sample data set
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]

high_temp_threshold = 26

high_temp_cities = [city for city in climate_data if city['temperature'] > high_temp_threshold]

print('Cities with high temperature (> 26°C):')
for city in high_temp_cities:
    print(f"{city['city']} - {city['temperature']}°C")


Cities with high temperature (> 26°C):
City B - 30°C
City E - 28°C


In [62]:
# Calculate the average carbon footprint
total_carbon_footprint = sum(city["carbon_footprint"] for city in climate_data)
average_carbon_footprint = total_carbon_footprint / len(climate_data)

print(f"Average carbon footprint: {average_carbon_footprint}")


Average carbon footprint: 420.0


In [70]:
# Find the city with the highest carbon footprint
highest_carbon_city = max(climate_data, key=lambda city: city["carbon_footprint"])

print(f"City with the highest carbon footprint: {highest_carbon_city['city']} with {highest_carbon_city['carbon_footprint']} units")


City with the highest carbon footprint: City C with 600 units


In [72]:
#Example usage:
# Function to calculate carbon footprint
def calculate_carbon_footprint(energy_consumption, emission_factor):
    return energy_consumption * emission_factor

# Example usage
energy_consumption = 1000  # in kWh
emission_factor = 0.475  # in kg CO2 per kWh
carbon_footprint = calculate_carbon_footprint(energy_consumption, emission_factor)
print(f"Carbon footprint: {carbon_footprint} kg CO2")



Carbon footprint: 475.0 kg CO2


In [82]:
# Define the sustainability threshold
sustainability_threshold = 400

# Filter the cities based on the carbon footprint
sustainable_cities = [city for city in climate_data if city["carbon_footprint"] < sustainability_threshold]
unsustainable_cities = [city for city in climate_data if city["carbon_footprint"] >= sustainability_threshold]

print("Sustainable cities:")
for city in sustainable_cities:
    print(f"{city['city']} - {city['carbon_footprint']} units")

print("\nUnsustainable cities:")
for city in unsustainable_cities:
    print(f"{city['city']} - {city['carbon_footprint']} units")


Sustainable cities:
City B - 350 units
City D - 200 units

Unsustainable cities:
City A - 500 units
City C - 600 units
City E - 450 units


In [10]:
#------------------------DAY 2-----------------------------------------------------------------------------------

In [12]:
is_leap_year = lambda year: year % 4 == 0 and (year % 100 != 0 or year % 400 == 0)
year = 2024
print(is_leap_year(year))  


True


In [36]:
import pandas as pd

In [42]:
import pandas as pd

renewable_sources = ['Solar', 'Wind', 'Hydropower', 'Geothermal', 'Biomass']
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}



In [32]:
renewable_series = pd.Series(renewable_sources)

print("Renewable Energy Sources:")
print(renewable_series)

Renewable Energy Sources:
0         Solar
1          Wind
2    Hydropower
3    Geothermal
4       Biomass
dtype: object


In [46]:
projects_df = pd.DataFrame(data)
projects_df.head()


Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [48]:
projects_df.tail()

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [58]:
projects_df.iloc[1:3]

Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
1             2024  
2             2022

In [60]:
selected_rows = projects_df.iloc[[1, 2]]


print(selected_rows)

          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
1             2024  
2             2022  


In [62]:
projects_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Project           5 non-null      object
 1   Technology        5 non-null      object
 2   Capacity (MW)     5 non-null      int64 
 3   Cost (Million $)  5 non-null      int64 
 4   Location          5 non-null      object
 5   Completion Year   5 non-null      int64 
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes


In [64]:
projects_df.describe()

Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000

In [72]:
#filter out the project whose capacity is more than 100 MW
filtered_df = df[df["Capacity (MW)"] > 100] 
print(filtered_df)

          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  


In [82]:
#add a new column to calculate the cost per megawatt for each project
df["Cost per MW ($/MW)"] = df["Cost (Million $)"]  / df["Capacity (MW)"] 
print(df)

              Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW ($/MW)  
0  California             2023            1.333333  
1       Texas             2024            1.333333  
2  Washington             2022            1.750000  
3      Nevada             2025            2.000000  
4       Idaho             2023            2.500000  


In [90]:

df = pd.DataFrame(data)

# Aggregate the data to find the total capacity and total cost
total_capacity = df["Capacity (MW)"].sum()
total_cost = df["Cost (Million $)"].sum()

print("Total Capacity (MW):", total_capacity)
print("Total Cost (Million $):", total_cost)


Total Capacity (MW): 800
Total Cost (Million $): 1300


In [96]:
# Group by technology and calculate total capacity for each type
grouped_df = df.groupby("Technology")["Capacity (MW)"].sum().reset_index()
print(grouped_df)


   Technology  Capacity (MW)
0  Geothermal            100
1  Hydropower            200
2       Solar            200
3        Wind            300


In [98]:
# Group by technology and calculate total capacity for each type
grouped_df = df.groupby("Technology")["Capacity (MW)"].sum().reset_index()

# Print the whole DataFrame
print("Original DataFrame:")
print(df)

# Print the grouped DataFrame
print("\nGrouped DataFrame (Total Capacity by Technology):")
print(grouped_df)


Original DataFrame:
              Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023  

Grouped DataFrame (Total Capacity by Technology):
   Technology  Capacity (MW)
0  Geothermal            100
1  Hydropower            200
2       Solar            200
3        Wind            300


In [100]:
import numpy as np

In [104]:
# One-dimensional array
one_d_array = np.array([1,2,3])
print(one_d_array)

[1 2 3]


In [108]:
# Two-dimensional array
two_d_array = np.array([[1,2],[3,4]])
print(two_d_array)

[[1 2]
 [3 4]]


In [110]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) 
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

(2, 3)
2
6
int32
4


In [114]:
ones_array = np.ones((2, 3))
print("Array of ones:\n", ones_array)

zeros_array = np.zeros((2, 3)) 
print("Array of zeros:\n", zeros_array)

random_array = np.random.random((3, 3)) 
print("Random array:\n", random_array)

Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Random array:
 [[0.74016581 0.91602212 0.49861924]
 [0.88385997 0.34270991 0.8795994 ]
 [0.98656891 0.97120727 0.3024892 ]]


In [116]:
arr = np.full((3,3),10)
print(arr)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [120]:
identity_arr = np.identity(5)
print(identity_arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [138]:
arr_with_arange = np.arange(0, 7, 2)
print(arr_with_arange)


[0 2 4 6]


In [140]:
import numpy as np
arr1 = np.arange(0, 10, 2)
print(arr1)

[0 2 4 6 8]


In [144]:
linespace_arr1 = np.linspace(5,10,3)
print(linespace_arr1)

[ 5.   7.5 10. ]


In [146]:
linespace_arr1 = np.linspace(2.2, 3.0, num=6, retstep = True)
print(linespace_arr1)

(array([2.2 , 2.36, 2.52, 2.68, 2.84, 3.  ]), 0.15999999999999998)


In [152]:
arr = np.array([1,2,3,4,6,3,9])
print(arr[0])
print(arr[1])

print('\n')
print(arr[:])

print('\n')
print(arr[::1])
print(arr[::2])
print(arr[::-1])

1
2


[1 2 3 4 6 3 9]


[1 2 3 4 6 3 9]
[1 3 6 9]
[9 3 6 4 3 2 1]


In [166]:
def is_palindrome(arr):
    if np.array_equal(arr, arr[::-1]):
        print("IS Palindrome")
    else:
        print("IS Not a Palindrome")

arr1 = np.array([1, 2, 3, 2, 1])
is_palindrome(arr1)


IS Palindrome


In [170]:
arr = np.array([1, 2, 3, 4, 6, 3, 9])

# Reshape into a valid shape, such as (7, 1) or (1, 7)
print(arr.reshape(7, 1))
print(arr.reshape(1, 7))


[[1]
 [2]
 [3]
 [4]
 [6]
 [3]
 [9]]
[[1 2 3 4 6 3 9]]


In [184]:
# Create a 2D array
arr = np.array([[1, 2], [4, 5], [7, 8]])

# Reshape the array into a different shape
reshaped_arr1 = arr.reshape(2, 3)
reshaped_arr2 = arr.reshape(3, 2)

print("Original array:\n", arr)
print("\nReshaped array (2, 3):\n", reshaped_arr1)
print("\nReshaped array (3, 1):\n", reshaped_arr2)


Original array:
 [[1 2]
 [4 5]
 [7 8]]

Reshaped array (2, 3):
 [[1 2 4]
 [5 7 8]]

Reshaped array (3, 1):
 [[1 2]
 [4 5]
 [7 8]]


In [186]:
# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpose the matrix
transpose_matrix = matrix.T
print("Original matrix:\n", matrix)
print("\nTranspose matrix:\n", transpose_matrix)


Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [190]:
arr = np.array([[1, 2,3], [4, 5,6], [7, 8,9]])
print(arr.flatten())

[1 2 3 4 5 6 7 8 9]


In [194]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the array in C order (row-major)
flattened_C = arr.flatten('C')
print("Flattened in C order:", flattened_C)

# Flatten the array in F order (column-major)
flattened_F = arr.flatten(order='F')
print("Flattened in F order:", flattened_F)


Flattened in C order: [1 2 3 4 5 6]
Flattened in F order: [1 4 2 5 3 6]


In [196]:
# Create an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Calculate the mean
mean = np.mean(arr)
print("Mean:", mean)

# Calculate the median
median = np.median(arr)
print("Median:", median)

# Calculate the standard deviation
std_dev = np.std(arr)
print("Standard Deviation:", std_dev)

# Calculate the variance
variance = np.var(arr)
print("Variance:", variance)


Mean: 5.0
Median: 5.0
Standard Deviation: 2.581988897471611
Variance: 6.666666666666667


In [198]:
# Create an array for energy consumption (in kWh)
energy_consumption = np.array([1200, 3400, 2900, 1800, 2500])

# Calculate the mean
mean_consumption = np.mean(energy_consumption)
print("Mean energy consumption (kWh):", mean_consumption)

# Calculate the median
median_consumption = np.median(energy_consumption)
print("Median energy consumption (kWh):", median_consumption)

# Calculate the standard deviation
std_dev_consumption = np.std(energy_consumption)
print("Standard deviation of energy consumption (kWh):", std_dev_consumption)

# Calculate the variance
variance_consumption = np.var(energy_consumption)
print("Variance of energy consumption (kWh):", variance_consumption)


Mean energy consumption (kWh): 2360.0
Median energy consumption (kWh): 2500.0
Standard deviation of energy consumption (kWh): 781.2809993849844
Variance of energy consumption (kWh): 610400.0


In [206]:
print(energy_consumption.reshape(5,1))

[[1200]
 [3400]
 [2900]
 [1800]
 [2500]]
